$activeBorderColor = rgb(00ffff)
$inactiveBorderColor = rgba(33333388)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
